### ISSUE TITLE
[TW#20360] Safe defaults for scan threshold and dwell time

### ISSUE THREAD

**Issue by devsaurus** [espressif/ESP8266_NONOS_SDK#103]
The structs `station_config` and `scan_config` in `include/user_interface.h` were augmented with new members in https://github.com/espressif/ESP8266_NONOS_SDK/commit/b4478720e5f12b78438dc8bb8d32b482b74734de#diff-3d8510b5f68b1ce4e40ea4515fff75e5

Is it sufficient to initialize with all-zero or do we have to set specific values in order to retain equivalent functionality compared to SDK 2.1.0? Please provide recommended default values for them.

**Comment by ustccw** [comment]
@devsaurus 
for `struct station_config`, you could set thresholds for signal and authmode, it will ignore the AP which below the thresholds. you could set `threshold.rssi = -127` and `threshold.authmode = AUTH_OPEN`

**Comment by ustccw** [comment]
@devsaurus 
for `scan_config`, the recommended default values  is up to  what you need. To do a balance between `accuray` and `total scan time`. such as in a strong network, you could set `scan_time.active.min=100` && `scan_time.active_max=300` for active scan, `scan_time.passive=100` for passive can.

**Comment by devsaurus** [comment]
Thanks for the recommendations @ustccw!

Regarding `scan_config`: We will probably expose this API on Lua level for the nodemcu firmware in the future so the user can balance based on his application scenario. Do I understand right that the settings
```c
scan_time.active.min=100
scan_time.active.max=300
scan_time.passive=100
```
reproduce the scan configuration for SDK 2.1.0, which didn't provide this config capability?

**Comment by devyte** [comment]
I apologize for jumping in, but I have a question on this same topic.
What happens if the following is set:
```
scan_time.active.min=0;
scan_time.active.max=0;
scan_time.passive=0;
```
?

**Comment by kriegste** [comment]
This is how I interpret the original question:

What were the defaults in earlier SDK versions, when we did not have these options?

**Comment by ustccw** [comment]
@devsaurus @devyte @kriegste Hi, the following is a set of test reference data, testing under the weak network.

1) passive scan in networking mode(ESP8266 got ip):  
![20171130172818681](https://user-images.githubusercontent.com/24221485/39104741-4717242c-46e4-11e8-83f5-287dd4a626fe.png)

2) passive scan in non-networking mode(ESP8266 without ip):
![20171130172112214](https://user-images.githubusercontent.com/24221485/39104785-8555c144-46e4-11e8-9efe-97e896a4cea9.png)

3) active scan in networking mode:
![20171130165622864](https://user-images.githubusercontent.com/24221485/39104825-b640cf06-46e4-11e8-96e1-c504941695d2.png)

4) active scan in non-networking mode:
![20171130165909757](https://user-images.githubusercontent.com/24221485/39104842-c21ec35a-46e4-11e8-9adf-927a56b40f6a.png)

**Comment by ustccw** [comment]
@kriegste the defaults in earlier SDK versions:
passive: 120 ms
active.min: 60 ms
active.max: 120ms

**Comment by ustccw** [comment]
@devsaurus yes, and it is up to your networking.

**Comment by devyte** [comment]
@ustccw thank you very much for this information! It is a big help for understanding the scan times!

**Comment by devsaurus** [comment]
@ustccw thank you very much for the valuable information!
