### ISSUE TITLE
使用esp-mqtt-proj时TCP: Disconnected callback MQTT: Disconnected

### ISSUE THREAD

**Issue by limuzi2012** [espressif/ESP8266_NONOS_SDK#104]
WIN10本地建了个emqtt服务器,然后一直接收到以下信息

[00:17:57.300]收←◆Free memory
TCP: Connect to ip  192.168.0.105:8083
TCP: Reconnect to: 192.168.0.105:8083
MQTT: Connected to broker 192.168.0.105:8083
MQTT:Sending,type:1,id:0000
TCP: Sent
TCP: data received 158 bytes
TCP: Disconnected callback
MQTT: Disconnected

试了几个版本的sdk都是如此,这是什么意思?怎么解决?

**Comment by xuhongv** [comment]
收到数据之后断开连接了，查看代码啊

**Comment by limuzi2012** [comment]
不知道是什么意思,这个是没有连接上mqtt服务器的试连接,还是连接上了之后的保持连接过程,我抓数据分析发现应该是前面一种情况,

**Comment by limuzi2012** [comment]
端口设置问题,端口设置错了
