### ISSUE TITLE
Some drivers can not be compiled from the NO_SDK 2.1.0

### ISSUE THREAD

**Issue by Michel-XU** [espressif/ESP8266_NONOS_SDK#11]
Some interrupt handlers can not be compiled in the drivers, for example, using the <key.c>.
The result in follow:
![capture](https://cloud.githubusercontent.com/assets/27750184/26440772/6330faaa-4160-11e7-94af-a627ca0f41fe.PNG)

If the <key.c> from the examples IoT_Demo, it can be compiled.
The different is the parameter of the function: 
key_intr_handler(struct keys_param *keys): in driver
key_intr_handler(void *arg): in IoT_DEMO

**Comment by FayeY** [comment]
Hi, this problem should be fixed in the latest SDK, please have a try.
