### ISSUE TITLE
[TW#20496] Fix system relative time not accurate ?

### ISSUE THREAD

**Issue by someburner** [espressif/ESP8266_NONOS_SDK#117]
Hi,

> @wujiangang committed 2 days ago
> Fix system relative time not accurate
> internal gitlab: 2f111e2e

As per the title, could we get a brief description of this fix and what was wrong before? My application is highly sensitive to timing- we use system microseconds to maintain sync with another radio, and there are cryptographic implications as well.

**Comment by wujiangang** [comment]
hi, @someburner it's only impact the API `system_relative_time`. The result seems like `new time - old time`, but in old implement, `new time` is not right, it should add an offset, so the relative time is not accurate, now, the result likes `new time + offset - old time.

Hope it's useful for you.
