### ISSUE TITLE
questions about at_sdio example 

### ISSUE THREAD

**Issue by rillhu** [espressif/ESP8266_NONOS_SDK#118]
Hi Expert,
Could you pleaseshare more info about the at_sdio example? 

How could I run this example? Should be it run on esp-wroom-s2? And need a MCU as a host?

Could you please provide more info?

**Comment by xcguang** [comment]
Yes, It should run esp-wroom-s2 and need a MCU as a host.
MCU need do something to boot esp-wroom-s2.

**Comment by xcguang** [comment]
Close it because of no update for a long time, if you have any question, please reopen it again.

**Comment by nimaltd** [comment]
I cant find boot file for sdio
