### ISSUE TITLE
[TW#20762] RF_NO_CAL deep sleep option does not work since sdk 1.5.1_16_01_08

### ISSUE THREAD

**Issue by mailgpa** [espressif/ESP8266_NONOS_SDK#122]
```
system_deep_sleep_set_option(RF_NO_CAL);
system_deep_sleep(1000000);
```

startup time after deep sleep is around 200ms

for more details refer to https://github.com/esp8266/Arduino/issues/3408

**Comment by torntrousers** [comment]
Hi, any ideas on this or if its likely to get fixed?

**Comment by mailgpa** [comment]
Seems to be an issue in Arduino core, see https://github.com/esp8266/Arduino/issues/3408#issuecomment-413094948 and https://github.com/esp8266/Arduino/issues/3408#issuecomment-413661491
