### ISSUE TITLE
TLS 1.2

### ISSUE THREAD

**Issue by johnnyodonnell** [espressif/ESP8266_NONOS_SDK#14]
Does this SDK support TLS 1.2 yet?

**Comment by wujiangang** [comment]
@johnnyodonnell We've pushed the mbedTLS code and pre-compiled libmbedtls.a, TLS 1.2 can be supported. If you want to use libmbedtls.a, modify your Makefile, change `-lssl` to `-lmbedtls`.

**Comment by johnnyodonnell** [comment]
Thanks @wujiangang! Also, just for reference, the mbedTLS package can be found here: https://espressif.com/en/products/hardware/esp8266ex/resources
