### ISSUE TITLE
sleep issues of high current still there. 

### ISSUE THREAD

**Issue by devlinhtran** [espressif/ESP8266_NONOS_SDK#140]
Dear Espressif, 
I am Linh from Freelux. We are working with many your wifi chip Esp8266 in our project. I saw the high current problem in long time ago, but i don't know how to fix it. To day when i recheck your new version note, i am very happy when see you fix that problem in V2.2.1. But when i test, that problem seem still there. 
From datasheet, I know that Esp8266's RF will auto go sleep mode when chip Idle state and auto wak-up to save energy. I checked SDK v2.2.1 about the current. I saw the current always  more than 80mA. That current is so height and i don't see the chip try to save energy in long time as old version.
At the old version V2.0.0 the current at the first start up time about more than 80 mA but it will reduce to 40mA, after a half minus it comeback about 80mA again (i don't know why), the period time spend on wifi connection. So the v2.0.0 work but have bug.
I saw in your release note: "Fix light sleep issues of high current and fail to sleep in some cases" . Can you tell me what exactly do you fix? and how much current spend in normal mode? How can i setting to have current about 40-50mA in normal mode?
Regards 
LinhTran
Freelux

**Comment by xcguang** [comment]
Close it because there is no update for a long time.
