### ISSUE TITLE
"feat(system): add exception handler for load store exception " breaks my project

### ISSUE THREAD

**Issue by ataweg** [espressif/ESP8266_NONOS_SDK#142]
update from commit 67bdd07 to c766134 breaks my project.
I get much more free heap (38880 --> 74280) but my exception handler doesn't work as before.
Update to HEAD revision, except libmain.a, my project works as before. This is probably due to the changes in libmain.a. 
What has been changed to libmain.a? Do I have to adjust my interrupt hnadler? Which role does the larger heap play?

see also my comment in https://github.com/espressif/ESP8266_NONOS_SDK/commit/c76613457be934856bc3bcfce7117eb00300e020#comments

Viele Gruesse
Axel

**Comment by xcguang** [comment]
Hi,
Could you give some log and the code about interrupt handler?

**Comment by ataweg** [comment]
I played a litlte bit around with using MEMLEAK_DEBUG and replacing os_malloc() with os_malloc_dram() in my user code:
1) using os_malloc() failed as reported above
2) using os_malloc_dram() works as before
3) using os_malloc()  and MEMLEAK_DEBUG defined works as before
4) using os_malloc_dram()  and MEMLEAK_DEBUG defined failed also

changed in mem.h
#define os_calloc( l, s)      pvPortCalloc( l, s, "", __LINE__)
case 1) works as before but case 4) fails

**Comment by ataweg** [comment]
Here my file with the interrupt handler which fails
[keys.c.txt](https://github.com/espressif/ESP8266_NONOS_SDK/files/2177383/keys.c.txt)

For a short press on the button the debug msg in the case it fails is:
D (0:00:14.004) keys(198): Key pressed  (0x40107cc0) 2820496246
D (0:00:14.170) keys(169): Key released (0x40107cc0) 2820496396
D (0:00:14.170) keys(177): Registered a very long press 2820496396
D (0:00:14.171) user/user_button.c(96): buttonVeryLongPress

But it should be:
D (0:00:13.927) keys(198): Key pressed  (0x40107530) 0
D (0:00:14.110) keys(169): Key released (0x40107530) 150
D (0:00:14.110) keys(187): Registered a short press 150
D (0:00:14.110) user/user_button.c(73): buttonShortPress

Since it worked before, my interrupt handler cannot be so wrong.

**Comment by xcguang** [comment]
Hi @ataweg ,
I want to reproduce the issue, but I can't run your code. And I test examples/wps, it works well.
Can you try this example? Or give me a complete demo that I can reproduce the problem?

**Comment by ataweg** [comment]
Hi Xcguang,
I created a small demo based on the wps example. It doesn't show the issue. It's too small and uses only one os_malloc call. You can get it but I think it would not help here. I use there  the toolchain sysgcc from sysprogs.com on a windows 10 computer. 
For my big project I changed mem.h and it works as descripted in one of the comments above. 
I don't think this is a problem of the interrupt handler, much more I bet on a problem with the memory management. What surprises me is the dependency of mem.h. This should not exclude that my project has no mistakes.
If it helps you and you have a NodeMCU, I can provide you with my project.
Viele Gruesse
Axel

**Comment by ataweg** [comment]
see https://github.com/ataweg/IoT-Wifi-Switch
When you rename in the include folder mem.h_ to mem.h  the project works fine.
Have fun
Axel

**Comment by ataweg** [comment]
I updated to ESP8266_NONOS_SDK commit ed3f217, but the issues is still there. I got some crasches:

Fatal exception 28(LoadProhibitedCause):
epc1=0x4010103a, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000000, depc=0x00000000
--> 0x40101028                xPortGetMinimumEverFreeHeapSize

Fatal exception 9(LoadStoreAlignmentCause):
epc1=0x40100d73, epc2=0x00000000, epc3=0x00000000, excvaddr=0x067bf669, depc=0x00000000
--> 0x40100cd4                pvPortMalloc

Fatal exception 9(LoadStoreAlignmentCause):
epc1=0x4010103a, epc2=0x00000000, epc3=0x00000000, excvaddr=0x0003aaaa, depc=0x00000000
--> 0x40101028                xPortGetMinimumEverFreeHeapSize

Fatal exception 9(LoadStoreAlignmentCause):
epc1=0x40100c85, epc2=0x00000000, epc3=0x00000000, excvaddr=0x0000000d, depc=0x00000000
--> 0x40100c80                prvRemoveBlockFromUsedList

Fatal exception 28(LoadProhibitedCause):
epc1=0x40100c85, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00148000, depc=0x00000000
--> 0x40100c80                prvRemoveBlockFromUsedList

It helps when I change in mem.h to
#define os_calloc(l, s)   pvPortCalloc(l, s, "", __LINE__)
#define os_zalloc(s)      pvPortZalloc(s, "", __LINE__)

**Comment by ataweg** [comment]
I updated to ESP8266_NONOS_SDK commit https://github.com/espressif/ESP8266_NONOS_SDK/commit/efa7981fc3b4ef03005a0521f112265c1dc6b9df. It's better now, but the problem is still there, if you press the button shortly, the very_long_press handler is called by mistake. 
It seems something is going wrong when using pvPortCallocIram() or pvPortZallocIram(). When I replace them with pvPortCalloc() or pvPortZalloc() in mem.h my project works fine. Press the button shortly calls the short_press handler.

**Comment by ataweg** [comment]
Issue fixed. It was my fault. 
It was one of the kind of errors that only occur when there are changes in the underlying requirements. In this case, it was a change in memory management that resulted in more free memory. 
I found the error by gradually adding my functions to the WPS example until the error occurred. So it was an easy thing to encircle the error. The DBG debugger was unfortunately not helpful here.

The new memory management has the disadvantage that debugging with GDB and gdbstub no longer works, since gdbstub intercepts the SIGSEGV exception handler. However, this is required for the new memory management to correct memory misalignment. This is where espresso must be reworked. Otherwise debugging with GDB and gdbstub will be a bit difficult.

One more word about the examples of the ESP8266_NONOS_SDK: in their current form they cannot be used out-of-the-box. It does not describe under which toolchain they are built, nor are they correctly configured. For example, the top-level Makefile is one folder too high, it belongs in the example folder. I just have to say, espressif did a sloppy job here. Since I use the SysGCC toolchain I have revised the wps example. You can find them at https://github.com/ataweg/ESP8266-NONOS-SDK_Examples. From time to time I will also update the other examples.
