### ISSUE TITLE
compiler error when using MEMLEAK_DEBUG 

### ISSUE THREAD

**Issue by ataweg** [espressif/ESP8266_NONOS_SDK#143]
because in mem.h  
1) type bool is not defined
2) no prototype for pvPortCalloc()

fix: 
1) add  #include <c_types.h>         // bool
2) add  void *pvPortCalloc( size_t, size_t, const char *, unsigned );

Viele Gruesse
Axel

**Comment by xcguang** [comment]
Hi @ataweg,
We will fix these, Thanks!

**Comment by xcguang** [comment]
Hi @ataweg ,
Please retry the latest version, thanks.

**Comment by xcguang** [comment]
Hi @ataweg ,
We will close the issue because of no update for a long time. @FayeY
