### ISSUE TITLE
can't scandone ssid   !!!!!

### ISSUE THREAD

**Issue by yj84949657** [espressif/ESP8266_NONOS_SDK#146]
mac :5c:cf:7f:76:e0:2a
[esp_set_station_config]-532:startCnt wifi connecting 1073649188
[user_init]-218:wifi http client 
mode : sta(5c:cf:7f:76:e0:2a)
add if0
scandone
no z24 found, reconnect after 1s
reconnect
scandone
no z24 found, reconnect after 1s
reconnect
scandone

**Comment by xcguang** [comment]
Hi,
Is the AP 5G or 2.4G?

**Comment by xcguang** [comment]
Close it because there is no reply for a long time.
