### ISSUE TITLE
[TW#25950] c_types.h - sint32_t and int32_t are inconsistent

### ISSUE THREAD

**Issue by davydnorris** [espressif/ESP8266_NONOS_SDK#150]
In c_types.h, the definition of sint32_t doesn't match int32_t, and is inconsistent with the other integer defintions:

Currently it's:
```
typedef signed long  sint32_t;
typedef signed int  int32_t;

```
it should be:
```
typedef signed int sint32_t;
typedef signed int int32_t;
```

**Comment by xcguang** [comment]
Hi,
Have fixed it in commit 6d79fef9a and 5b0af8ff.
