### ISSUE TITLE
why should be #pragma pack(1) in spi_interface.h ? doesn't it be 4 bytes per pack when do memory operation?

### ISSUE THREAD

**Issue by 9crk** [espressif/ESP8266_NONOS_SDK#151]
why should be #pragma pack(1) in spi_interface.h ? doesn't it be 4 bytes per pack when do memory operation?

I change it to be 4 then my program runs normal.

**Comment by xiongyumail** [comment]
Hi @9crk ,
We use pack (1) to save memory. Can you provide an example with the mistake for us?

**Comment by xcguang** [comment]
Close it because of no update for a long time.
