### ISSUE TITLE
how to set hspi

### ISSUE THREAD

**Issue by Martin8023** [espressif/ESP8266_NONOS_SDK#152]
i make the example but no hspi clk and in the example of user_config.h is nothing if make it will error.

**Comment by xcguang** [comment]
[esp8266_hspi.zip](https://github.com/espressif/ESP8266_NONOS_SDK/files/2247893/esp8266_hspi.zip)

Hi @Martin8023 ，
Here is a Hspi example for AT, maybe it will help you.

**Comment by Martin8023** [comment]
OK,thanks @xcguang .I'll try.

**Comment by xcguang** [comment]
Hi @Martin8023 ,
We will close the issue firstly, if you have any question, please reopen it or create a new issue. @FayeY
