### ISSUE TITLE
ESP8266 - WiFi Rx Sensitivity

### ISSUE THREAD

**Issue by chlo12345678** [espressif/ESP8266_NONOS_SDK#154]
Can we change the WiFi sensitivity of ESP8266?
Can it be adjusted such that the receive range can be extended?
Is so, how to do? Is there any AT-command for this?

**Comment by xcguang** [comment]
@FayeY

**Comment by FayeY** [comment]
Hi, sorry that the WiFi RX sensitivity is not configurable, cannot be extended. You can find the WiFi RX sensitivity in the [ESP8266EX datasheet](https://www.espressif.com/sites/default/files/documentation/0a-esp8266ex_datasheet_en.pdf). Thanks.
