### ISSUE TITLE
libraries compiled with -ffunction-sectons -fdata-sections .....

### ISSUE THREAD

**Issue by MaBecker** [espressif/ESP8266_NONOS_SDK#156]
can you provide libs without this this features like in version 2.1?

* libm.a into .irom0.text;

* compiled some libraries with -ffunction-sectons -fdata-sections;

* modified ld to put this.text.* into .irom0.text

**Comment by kriegste** [comment]
Can you tell us why you need that?

**Comment by MaBecker** [comment]
Well, since Building Espruino with 2.2 ld  complains about to to large text section as Espruino is also using this section.

**Comment by MaBecker** [comment]
Update:

targets/esp8266/espmissingincludes.h
replaced  targets/esp8266/eagle.app.v6.new.2048.ld 

and no more link errors when using SDK 2.2
