### ISSUE TITLE
Include math lib

### ISSUE THREAD

**Issue by kriegste** [espressif/ESP8266_NONOS_SDK#16]
Hi,

please include the math lib in the NONOS SDK so we can use sin, cos, asin, atan2 and the like.

Please compile this and all the other libs with parameters -ffunction-sections -fdata-sections which will open a chance to shrink the images down quite a bit. 512kB are often a bit tight.

Thank you very much for your great work!

**Comment by wujiangang** [comment]
hi, @kriegste 

If you want to use math functions, you can add -lm in your Makefile, and include math.h in your source code.

**Comment by kriegste** [comment]
The problem with the standard -lm is...

> /opt/Espressif/esp-open-sdk/xtensa-lx106-elf/lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld: build/httpd.user1.out section `.text' will not fit in region `iram1_0_seg'

I think in the RTOS SDK you included an irom version of lib m. My request would be to include this in the NONOS SDK as well.

**Comment by wujiangang** [comment]
OK, got your point, will update soon.

**Comment by kriegste** [comment]
Thanks!

**Comment by wujiangang** [comment]
Please test commit: 33d4ee2

**Comment by kriegste** [comment]
Compilation works and calculations seem to be correct, thank you very much!

**Comment by wujiangang** [comment]
Great, compile libs with parameters -ffunction-sections -fdata-sections will be committed soon. This is a topic of #13 .
