### ISSUE TITLE
ESP8266 - I2C DS3231 Fail 

### ISSUE THREAD

**Issue by minhhieuec** [espressif/ESP8266_NONOS_SDK#160]
Hi espressif!
i tried user_sensor example IoT_Demo for DS3231, I repaired 0x88 (MVH3004_Addr) to 0x68 (DS3231 Addr), after that i read 7 bytes from i2c bus. But, when call user_mvh3004_burst_read() function, it return false - (no ACK os_printf("addr not ack when tx write cmd \n");).

here is my code:

#include "ets_sys.h"
#include "osapi.h"
#include "user_interface.h"
#include "driver/uart.h"
#include "gpio.h"
#include "connect.h"
#include "ds3231.h"
#include "i2c_master.h"

#define printf(x) os_printf(x)

uint32 ICACHE_FLASH_ATTR
user_rf_cal_sector_set(void)
{
    enum flash_size_map size_map = system_get_flash_size_map();
    uint32 rf_cal_sec = 0;

    switch (size_map) {
        case FLASH_SIZE_4M_MAP_256_256:
            rf_cal_sec = 128 - 5;
            break;

        case FLASH_SIZE_8M_MAP_512_512:
            rf_cal_sec = 256 - 5;
            break;

        case FLASH_SIZE_16M_MAP_512_512:
        case FLASH_SIZE_16M_MAP_1024_1024:
            rf_cal_sec = 512 - 5;
            break;

        case FLASH_SIZE_32M_MAP_512_512:
        case FLASH_SIZE_32M_MAP_1024_1024:
            rf_cal_sec = 1024 - 5;
            break;

        case FLASH_SIZE_64M_MAP_1024_1024:
            rf_cal_sec = 2048 - 5;
            break;
        case FLASH_SIZE_128M_MAP_1024_1024:
            rf_cal_sec = 4096 - 5;
            break;
        default:
            rf_cal_sec = 0;
            break;
    }

    return rf_cal_sec;
}

void ICACHE_FLASH_ATTR
user_rf_pre_init(void)
{
}

void ICACHE_FLASH_ATTR
user_mvh3004_init(void)
{
    i2c_master_gpio_init();
}

bool ICACHE_FLASH_ATTR
user_mvh3004_burst_read(uint8 addr, uint8 *pData, uint16 len)
{
    uint8 ack;
    uint16 i;

    i2c_master_start();
    i2c_master_writeByte(addr);
    ack = i2c_master_getAck();

    if (ack) {
        os_printf("addr not ack when tx write cmd \n");
        i2c_master_stop();
        return false;
    }

    i2c_master_stop();
    i2c_master_wait(40000);

    i2c_master_start();
    i2c_master_writeByte(addr + 1);
    ack = i2c_master_getAck();

    if (ack) {
        os_printf("addr not ack when tx write cmd \n");
        i2c_master_stop();
        return false;
    }

    for (i = 0; i < len; i++) {
        pData[i] = i2c_master_readByte();

        i2c_master_setAck((i == (len - 1)) ? 1 : 0);
    }

    i2c_master_stop();

    return true;
}

// convert binary coded decimal to normal decimal
static uint8 ICACHE_FLASH_ATTR bcdToDec(uint8 bcd) {
  return(((bcd / 16) * 10) + (bcd % 16));
}

void ICACHE_FLASH_ATTR
user_init(void)
{
   uint8 i = 0;
   uint8 data[7];
   bool check = false;
   uart_init(115200, 115200);

   os_delay_us(20000);

   i2c_master_gpio_init();

   while(1) {
   
       check =  user_mvh3004_burst_read(DS3231_I2C_ADDRESS, data, 7);

       if (check == true) {
           os_printf("read time ok\r\n");
       }else{
           os_printf("read time fail\r\n");
       }

       os_printf("\r\n second: %d\r\n", bcdToDec(data[0]));
       os_printf("\r\n hour: %d\r\n", bcdToDec(data[2]));

       os_delay_us(1000);
   }
}

Could you help me to fix it?

**Comment by davydnorris** [comment]
This device uses clock stretching on the I2C bus. The default I2C driver code in the SDK doesn't implement clock stretching. This is why it's failing.

There are several implementations out there that have clock stretch. Contact me if you want mine, which is based on Pete Scargill's code

**Comment by minhhieuec** [comment]
@davydnorris  thanks for your information,
Please send to me your example code or document of this?
My Email: minhhieuec@gmail.com

best regard!

**Comment by valkuc** [comment]
I'm using https://github.com/pasko-zh/brzo_i2c in several projects. It's support clock stretching and work stable at 400 Khz speed.

**Comment by eriksl** [comment]
My I2C code also supports a wide variety of I2C "quirks". Every now and then I attach an oscilloscope to see if it really does what it should do. For 100 kHz standard mode on 80 MHz cpu and 400 kHz fast mode on 160 MHz, it takes care to only use proper timings, i.e. only change SDA when SCL is exactly in the middle of a cycle and prevent glitches of > 100 or > 400 kHz. It of course also supports clock stretching and faulty devices that tend to loose bits every now and then and not releasing the bus in time.

https://github.com/eriksl/esp8266-universal-io-bridge

The I2C code delivered as "example code" with the SDK is very poor.

**Comment by devyte** [comment]
@eriksl your repo is licensed under GPL, and I understand that makes it incompatible with Espressif's sdk for any project that requires distribution. That means only personal projects could make use of it.
If you would like a wider audience, I suggest changing the license to LGPL, MIT-like, or similar.

**Comment by eriksl** [comment]
I never understood the exact semantics of GPL vs. LGPL vs. MIT etc.

On the other hand, I do endorse the spirit of GPL where open source remains true open source. I fear that if I change the license to LGPL or MIT, my code can end up somewhere in a commercial project without that code being open. Ask the ffmpeg developers what happens... I don't want that. I do this in my spare time, so I think I may ask something in return (i.o.w. your code).

As long as that is guaranteed, I am open to changing the license.

**Comment by eriksl** [comment]
What a strange conclusion?

**Comment by marcelstoer** [comment]
This discussion is quickly getting OT. I'll keep it short.

> I fear that if I change the license to LGPL or MIT, my code can end up somewhere in a commercial project without that code being open.
> I never understood the exact semantics of GPL vs. LGPL vs. MIT etc.

Not being a subject matter expert myself it's hard to judge but I think you understand quite well. GPL is the right choice then for you.

> Erik, in this case it is better not to advertise your code.

Nonsense, what has one got to do with the other? Are you seriously suggesting [popular GPL projects](https://en.wikipedia.org/wiki/Category:Software_using_the_GPL_license) like WordPress, MariaDB, Ansible et.al. better kept their code to themselves?
