### ISSUE TITLE
ESP8266 light-sleep: how to get it?

### ISSUE THREAD

**Issue by shw19791031** [espressif/ESP8266_NONOS_SDK#165]
## Environment

esp8266ex (ESP-12S)

## Application

- Waiting for incoming MQTT packet to boot the master device, use battery.
- So deep-sleep is useless, I have to use light-sleep keeping MQTT connection.

## Problem Description
- forced light sleep: ok!, 0.7~0.8mA current, but WIFI have to be disconnected. It is worse than deep-sleep.
- automatic light sleep: never success!, because I cannot manually halt (control) the CPU while DTIM period.

### Dear Espressif!

Please help me!

**Comment by xcguang** [comment]
Hi,
What the current is when automatic light sleep? And the following api may be helpful.
```
bool wifi_set_sleep_level(enum sleep_level level);
enum sleep_level wifi_get_sleep_level(void);
bool wifi_set_listen_interval(uint8 interval);
uint8 wifi_get_listen_interval(void);
```
https://www.espressif.com/sites/default/files/documentation/2C-ESP8266_Non_OS_SDK_API_Reference__EN.pdf

**Comment by shw19791031** [comment]
Thanks for your response, Mr. xcguang.
I have tested with following code.

    wifi_set_sleep_level(MAX_SLEEP_T);
    wifi_set_listen_interval(10);
    wifi_set_sleep_type(LIGHT_SLEEP_T);

My router's DTIM is 10.
Measured current is 15.20 mA.

My question:
- Is 15.20mA the minimum?
- Is there a way to halt the CPU manually on Non-OS SDK?

Thanks! 谢谢！

**Comment by xcguang** [comment]
Hi,
1. It seems 15.20mA is the current of modem sleep.
2. There is no api to halt the CPU manually.

Could you provide your test code?

**Comment by shw19791031** [comment]
Hi,

- clone current ESP8266_NONOS_SDK.
- copy "esp_mqtt_proj" to "ESP8266_NONOS_SDK" root folder.
- modify "user_main.c", as attached.
[Report.zip](https://github.com/espressif/ESP8266_NONOS_SDK/files/2322661/Report.zip)


- modify “mqtt_config.h”, only MQTT_HOST, MQTT_CLIENT_ID, STA_SSID, STA_PASS.
- run "gen_misc.sh"

like this.
Please check it and reply with modified "user_main.c".

Thank you!

**Comment by shw19791031** [comment]
Hi, Mr. xcguang!

I want you to modify ESP8266_NONOS_SDK/esp_mqtt_proj supporting light-sleep with minimum power ,by default, and commit it to git repo.

Thank you!

**Comment by shw19791031** [comment]
Hi, @ustccw 

Non-OS SDK does not have **esp_wifi_set_ps**, please check it.

Thank you!

**Comment by shw19791031** [comment]
OK, [rtos issue 290](https://github.com/espressif/ESP8266_RTOS_SDK/issues/290#issuecomment-416787056), has discussed completely, thank you.
