### ISSUE TITLE
Description	Resource	Path	Location	Type make: *** [Makefile:309: .subdirs] Error 2	ESP8266_NONOS_SDK-2.0.0		 	C/C++ Problem

### ISSUE THREAD

**Issue by dingyu58** [espressif/ESP8266_NONOS_SDK#169]
Description	Resource	Path	Location	Type
make: *** [Makefile:309: .subdirs] Error 2	ESP8266_NONOS_SDK-2.0.0		 	C/C++ Problem
这个是什么原因

**Comment by xcguang** [comment]
请先 clean 一下，或者手动将每个文件夹下的 .output 删除，再编译试试

**Comment by xcguang** [comment]
@dingyu58 请问，此问题解决了吗？

**Comment by xcguang** [comment]
由于长时间没有更新状态，将关闭此 issue
