### ISSUE TITLE
[N8266-20] jsonparse_strcmp_value compare wrong length

### ISSUE THREAD

**Issue by schmidtandreas** [espressif/ESP8266_NONOS_SDK#173]
Hi,
I'm not sure if I'm right here or should create new issue on [contiki](https://github.com/contiki-os/contiki).
I try it here at first, because I use the esp8266 sdk and not contiki stuff.

Issue:
If you use "jsonparse_strcmp_value(struct jsonparse_state *state, const char *str)" for compare expected value, jsonparse only compare the length of "state" value. But it is not what you normally expect.
 Use case: If I'm searching for "brightness" and json data contain "b" (e.g. in "color" object), the "jsonparse_strcmp_value" will return 0, because in this case it compares only 1 character and this character match. But, I guess, it's not that, what you normally expect, isn't it?

**Comment by xcguang** [comment]
Please try it again using the latest master branch. I will sync at release/v3.0.0 and release/v2.2.x later.

**Comment by xcguang** [comment]
Hi,
I will close this issue, and you can reopen it if the problem persists.
BTW, we have opened json source code.
