### ISSUE TITLE
Noob question ;)

### ISSUE THREAD

**Issue by andrethomas** [espressif/ESP8266_NONOS_SDK#183]
Where do the files in https://github.com/espressif/ESP8266_NONOS_SDK/tree/master/lib come from? Can they be recompiled from some other repo or is it just released "As-is" ?

Thanks

**Comment by kriegste** [comment]
Only liblwip and libmbedtls are open-source (third_party folder).

**Comment by andrethomas** [comment]
Thanks, I thought as much - pitty its closed source on that level as it would have made room for a lot of optimization.
