### ISSUE TITLE
[DOC/PDF] Dead links into ESP8266 SDK Getting Started Guide

### ISSUE THREAD

**Issue by ThomArmax** [espressif/ESP8266_NONOS_SDK#187]
In the _ESP8266 SDK Getting Started Guide_ from the `README.md` file, in "_B.1. Must-Read Documents_" and '"_B.2. Must-Have Resources_" sections
- ESP8266 Hardware Resources
- ESP8266 AT Instruction Set
- ESP8266 Non-OS SDK API Reference
- ...

Leads to `404` error or "_There were no results found for this search query_"

**Comment by xcguang** [comment]
@FayeY

**Comment by FayeY** [comment]
Hi @ThomArmax , sorry for the inconvenience, the link is too old, we will update it asap. Before that, you can find our documents in [Espressif website](https://www.espressif.com/en/support/download/documents)
By the way, are you a new user of ESP8266? If it is, we suggest that you get started with our [RTOS SDK](https://github.com/espressif/ESP8266_RTOS_SDK) instead. The [ESP8266 RTOS SDK](https://github.com/espressif/ESP8266_RTOS_SDK) is in ESP-IDF style which can make your application able to run both on ESP32 and ESP8266, or porting to each other easily. Thanks.

**Comment by ThomArmax** [comment]
Hi @FayeY . Thanks ;) 
I have been working on the ESP8266/85 for about 6 months. I can't use the RTOS SDK since (if I well understoud when I have started the project), their is no AT  ability by default on the RTOS SDK (our products use the ESP as a coprocessor, and communicate with it using AT commands)
