### ISSUE TITLE
[N8266-19][AT 1.7.0] AT+ping takes long time

### ISSUE THREAD

**Issue by MaJerle** [espressif/ESP8266_NONOS_SDK#188]
calling `AT+PING="domain.com"` returns time in reasonable fast time. But after it returns time, it needs `> 1` second to report `OK<CR><LF>`

Why?

```
AT+PING="example.com"
<-- This takes < 100ms -->
+140
<-- This takes more than 1 second -->
OK
```

**Comment by MaJerle** [comment]
Hello team,

can we expect any feedback here?

Thanks.

**Comment by xcguang** [comment]
Hi @MaJerle ,
Have fix it, please try it again using the latest version.

**Comment by xcguang** [comment]
I will close this issue, if the problem persists, please reopen it again.

**Comment by MaJerle** [comment]
Thanks. I will wait for next official AT release and test on my library.
