### ISSUE TITLE
esp8266 sdk 2.2.1: system_deep_sleep causing reset

### ISSUE THREAD

**Issue by MopeZe** [espressif/ESP8266_NONOS_SDK#191]
Im using SDK 2.2.1

When running the following code:

```
system_deep_sleep_set_option(4);
system_deep_sleep(0);
```

ESP8266 immediately resets and doesnt enter deep sleep mode. 

Now what i really dont understand is if i run 

```
system_deep_sleep_set_option(4);
system_deep_sleep_instant(0);
```

everything works fine.

With SDK 2.0.0 system_deep_sleep() worked.

Can someone help? It is critical for us. 

Thanks and regards

**Comment by MopeZe** [comment]
Update: The issue happens if the ESP8266 is connected to a station. 

Can you comfirm this behaviour?

**Comment by xcguang** [comment]
@MopeZe ,
I  did test on the latest release/v2.2.x branch, it seems everything goes well. Could you try it again?
The following is my test code:
ESP8266 as SoftAP and one station connected ESP8266.
![image](https://user-images.githubusercontent.com/25979965/54329363-5b9d3900-464c-11e9-90bc-1707ffcdedf4.png)

ESP8266 as Station and connected an AP
![image](https://user-images.githubusercontent.com/25979965/54329409-87202380-464c-11e9-8bd7-947fd194ef80.png)

**Comment by xcguang** [comment]
Hi,
I will close this issue, and you can reopen it if the problem persists.
