### ISSUE TITLE
i2c_master.h missing #include "ets_sys.h"

### ISSUE THREAD

**Issue by nickagian** [espressif/ESP8266_NONOS_SDK#193]
In i2c_master.h there are function declarations that use the uint8 and bool types, but the compiler cannot find them. This can be solved by including the "ets_sys.h" file, which is anyway done in the i2c_master.c file.

**Comment by xcguang** [comment]
Hi @nickagian , 
Please try it using the latest branch. I will close this issue, you can reopen it if you have any question.
