### ISSUE TITLE
User proper commit messages on GitHub

### ISSUE THREAD

**Issue by marcelstoer** [espressif/ESP8266_NONOS_SDK#20]
I believe this says it all..

<img width="344" alt="useless-commit-messages" src="https://user-images.githubusercontent.com/624195/27688827-4a742680-5cdc-11e7-9e04-5d77f5e17c76.png">

It's not practical to open each commit to figure out what the changes actually were. The first line, ideally no more than 50 chars, should contain the essence of the commit.

**Comment by wujiangang** [comment]
Sometimes, the commit header cannot describe all modifications, since we will sync several changes from our internal gitlab, so just take this as a merge. If you want to know the changes well, use `git log` will show more info.

**Comment by marcelstoer** [comment]
> since we will sync several changes from our internal gitlab

I suspected that this is the reason but it doesn't _have_ to be that way. GitLab can be told to [automatically push changes to a remote repo](https://docs.gitlab.com/ee/workflow/repository_mirroring.html#pushing-to-a-remote-repository) such as GitHub.

> If you want to know the changes well, use `git log`

I know, but for casual observers (what most non-SDK developers are) this isn't practical because you'd have to clone the repository first.

You write [useful release notes](https://github.com/espressif/ESP8266_NONOS_SDK/releases) for people who are interested in the changes between release N and release N+1. Thanks for that. If I want to figure out what the changes since the latest release are I would look at the commit history as shown above.

**Comment by wujiangang** [comment]
The github repo is not a mirror of gitlab repo, so cannot use the way you provide. Now, it's some inconvenient for you, i will modify the commit way, thanks for your advise.
