### ISSUE TITLE
Output percent sign using os_printf

### ISSUE THREAD

**Issue by kriegste** [espressif/ESP8266_NONOS_SDK#200]
Anyone noticed this?

If we output a number and a percent sign with os_printf, a space is added after the percent sign.

Neither %% nor `\%` nor % alone works.

```
os_printf("%d% test\n", 1);
os_printf("%d%% test\n", 2);
os_printf("%d\% test\n", 3);
os_printf("%d%%test\n", 4);
```
Output:
```
1%  test
2%  test
3%  test
4% test
```

**Comment by FayeY** [comment]
Hi,

The `ets_printf` is in the chip ROM code, so we cannot modify it. And the firmware binary will become larger if we add a new `ets_printf` in the SDK. 
If you want to revise the `ets_printf`, you can implement a new `printf` referred to 
https://github.com/espressif/ESP8266_RTOS_SDK/blob/master/components/esp8266/source/ets_printf.c, or format the data using `ets_sprintf` and output the string, although this is not a very good way, as the following example:
```
{
    char data[64];
    os_sprintf(data,"%d%% test\n", 2);
    ets_printf(data);
}
```
Thanks.
