### ISSUE TITLE
AT problem

### ISSUE THREAD

**Issue by nimaltd** [espressif/ESP8266_NONOS_SDK#202]
I program like https://github.com/espressif/ESP8266_NONOS_SDK/tree/master/bin/at 
but don't answer  any at commands.
but when  i program ai thinker at version . its work.
i use esp-201 module with 32Mbit flash

**Comment by xcguang** [comment]
Hi,
Can you provide any log?

**Comment by nimaltd** [comment]
Hi.  Doesn't back any answer. 
I replace user1 with old version. Ad work fine

**Comment by nimaltd** [comment]
But i program with this methode   its work fine
Sam:
esptool.py -p COM2 --chip esp8266 write_flash -fm dio -ff 26m --flash_size 2MB-c1 0x00000 ./bin/boot_v1.7.bin 0x01000 ./bin/at/1024+1024/user1.2048.new.5.bin 0x1fc000 ./bin/esp_init_data_default_v08.bin 0xfe000 ./bin/blank.bin 0x1fe000 ./bin/blank.bin 0x1fb000 ./bin/blank.bin

**Comment by xcguang** [comment]
I guess I know the result about the issue. Since SDK3.0, we added check the flash_map, if the flash_map mismatch bin, it will fail. And we are considering removing this check.

**Comment by nimaltd** [comment]
I want try at_sdio.
But i can not find any sample by stm32

**Comment by xcguang** [comment]
https://github.com/espressif/ESP8266_NONOS_SDK/issues/203
this is a demo, maybe it is helpful.

**Comment by nimaltd** [comment]
thank you

**Comment by xcguang** [comment]
Hi @nimaltd ,
I will close the issue, if you have any question, please reopen it or create a new issue. Thanks.
