### ISSUE TITLE
AT 1.7.0 - AT+UART_DEF? always return 0 for every parameter

### ISSUE THREAD

**Issue by kurta999** [espressif/ESP8266_NONOS_SDK#213]
I've programmed AT firmware 1.7.0 to ESP-WROM-02 and AT+UART_DEF? always return 0 for every parameter. I tried it a few days ago, then setting baudrate to other was failed too. But today I was able to set baudrate to 921600 with AT+UARTDEF= command. It's interesting. After baudrate was set successfully, AT+UART_DEF? return correct values.

**Comment by xcguang** [comment]
Hi，
If you haven't sent AT+UART_DEF=xx command, the value in the flash is empty, so it returns 0.
If you want to query the current baudrate, you can send  AT+UART_CUR?

**Comment by xcguang** [comment]
Hi @kurta999 ,
I will close this issue, you can reopen it if the problem persists.
