### ISSUE TITLE
100ms Pause between +IPD 

### ISSUE THREAD

**Issue by Boodorgad** [espressif/ESP8266_NONOS_SDK#215]
# 100ms Pause between +IPD  

I see a big difference on IPD-Speed between Server and Client.

Using a **TCP-Server(AT+CIPSERVER)**, the ESP will send out the Data really fast and as described in the AT Instruction Set V3: 

>active mode - ESP8266 will send all the received TCP data instantly to host MCU through
>UART with header “+IPD".                    
                
But if you make a **TCP-Client(AT+CIPSTART)**, the ESP inserts 100ms Pause between IPD blocks?(Snapshot attached) 

The Result is a massiv lower Transfer-Speed for the TCP-Clients.   

I think it's not intend to work like this?

Used Versions
- SDK 3.0.0(e27cf60) 
- AT: 1.7.0.0(Aug 16 2018 00:57:04)

![ipd client](https://user-images.githubusercontent.com/12196024/53738415-6f4be100-3e8f-11e9-82fa-5cf434070cc4.jpg)

**Comment by xcguang** [comment]
Hi @Boodorgad ，
I did test, but it looks well.
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/25979965/54257655-fe957a80-459a-11e9-95af-4969ca629639.png">
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/25979965/54257701-2c7abf00-459b-11e9-955f-41174bef9f99.png">

**Comment by xcguang** [comment]
Hi,
Does it work well?  I will close this issue, and you can reopen it if the problem persists.
