### ISSUE TITLE
How to use IP6 in NONOS_SDK v3.0

### ISSUE THREAD

**Issue by Murphy2018** [espressif/ESP8266_NONOS_SDK#247]
Does NONOS_SDK support IP6 , or not? 
How I would do it? 
Thanks !

**Comment by FayeY** [comment]
IPv6？Sorry that nonOS SDK does not support IPv6. 
Would you like to have a try with our latest RTOS SDK？ It supports IPv6. https://github.com/espressif/ESP8266_RTOS_SDK/tree/master/examples/protocols/sockets
Thanks.
