### ISSUE TITLE
[AT] Check if STA static/DHCP IP in use

### ISSUE THREAD

**Issue by MaJerle** [espressif/ESP8266_NONOS_SDK#252]
Once device is connected to network and `WIFI GOT IP` message is received, what is the correct AT command to check if current IP configuration is `static` or via `DHCP`?

It is very confusing as multiple commands may influence & modify static/DHCP configuration.

**Comment by xcguang** [comment]
Maybe you can try `AT+CWDHCP_CUR?` to check whether DHCP is enable, if not, the ip is `static`.
