### ISSUE TITLE
AT固件：Light-sleep功耗无法达到1mA以下，已实测

### ISSUE THREAD

**Issue by fengfeng0328** [espressif/ESP8266_NONOS_SDK#264]
ESP-WROOM-02烧录SDK里面携带的AT固件，进入Light-sleep睡眠模式，但是平均功耗达到7mA，请问该问题应该如何解决？

相关AT指令：
AT+CWMODE_DEF=1
AT+CWJAP_DEF="djfiaiha","dfsadfkff"
AT+WAKEUPGPIO=1,0,1,13,1
AT+SLEEP=1

下面是测试接线图以及测试结果：
![image](https://user-images.githubusercontent.com/34309825/64917321-8ade5f80-d7c1-11e9-847e-a07662e247a1.png)
![image](https://user-images.githubusercontent.com/34309825/64917322-93cf3100-d7c1-11e9-98f1-edfdbb56b30f.png)

测试结果来自深圳市安信可科技有限公司，请提供解决方法，谢谢乐鑫！！

**Comment by xcguang** [comment]
平均功耗达不到 1 mA 以下，当前我们还正在 RTOS AT 上做优化，会有很大改善

**Comment by xcguang** [comment]
RTOS 对于功耗有很大改善，请采用 RTOS AT，谢谢
