### ISSUE TITLE
Poor +IPD design

### ISSUE THREAD

**Issue by MaJerle** [espressif/ESP8266_NONOS_SDK#27]
Hello team,

please check url below with ticket on ESP-32 AT. It would need check also for 8266.

https://github.com/espressif/esp32-at/issues/22

**Comment by exeron** [comment]
I agree. It should be checked as well for 8266, especially when the ESP can send data after you sent a command but before you get the first response.. in between you can receive data, but the command really started. Not the best to deal with...
