### ISSUE TITLE
WPS issue on SDK 3.0.1

### ISSUE THREAD

**Issue by esp-dev** [espressif/ESP8266_NONOS_SDK#270]
Hi,

I have issue with WPS on new SDK 3.0.1. WPS not working, and finally code is 23:
user_interface.h:    REASON_802_1X_AUTH_FAILED       = 23,  /* 11i */
log:
mode : sta(5c:cf:7f:XX:XX:XX)
add if0
wifi_wps_enable
wps scan
build public key start
build public key finish
wps discover [SSID]
scandone
WPS: neg start
mode: 0 -> 3
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 3
cnt
….wiat
state: 5 -> 2 (17c0)
rm 0
Disconn from SSID;23

On SDK 3.0.0 WPS work correctly.
Any idea? What different? How to make it working?

**Comment by hubciorz** [comment]
There seems to be a problem with this commit: 6580ca35e9f8f85d11100c1ad3d2ed27d4b26381
WPS stopped working on some APs

**Comment by kriegste** [comment]
Which routers are affected? Is Espressif working on this?

**Comment by Junhao-Espressif** [comment]
@hubciorz Could you try to connect to the AP directly with ssid and password to see if you can connect to it? 
Thanks!

**Comment by esp-dev** [comment]
AP chipset is Broadcom, connect manually by SSID/password works.

**Comment by Junhao-Espressif** [comment]
@esp-dev 

Could you provide more details about the AP? 
We will buy an AP for debugging.

Thank you!

**Comment by FayeY** [comment]
@hubciorz, could you list "some AP" that will fail with WPS? Maybe we can find the same APs to test and debug with the issue. Thanks.

**Comment by sjanek** [comment]
@Junhao-Espressif, @FayeY

**Comment by hubciorz** [comment]
@FayeY as stated above - there is a problem with Internet-Box 2 from Swisscom.

**Comment by Junhao-Espressif** [comment]
Hi @hubciorz 
Could you try with this lib on master version?

[libnet80211.zip](https://github.com/espressif/ESP8266_NONOS_SDK/files/3889738/libnet80211.zip)

**Comment by hubciorz** [comment]
@esp-dev could you try this one?

**Comment by esp-dev** [comment]
cloned commit: 4bf0aefee37ac1f272b793c2403c53a0c122b570 (branch v3.0.1, should I clone from master?)
replace libnet80211.a
**WPS working now.**
