### ISSUE TITLE
Specify connections for server

### ISSUE THREAD

**Issue by MaJerle** [espressif/ESP8266_NONOS_SDK#28]
When device is in server mode, it can happen that at some point, all connections are used for server and there is no support to use client mode at that time.

What we should have option to set is which connections are available for server.

Correct me if I'm mistaken, but current server approach is like this:

- User enables server at specific port
- ESP creates new connections and listens at specific port
- When connection is accepted, ESP creates new empty connection to listen on same port
- And so on, which means there is always one connection active and ready to accept new connection, except if we reached max connections.

We should be able to limit the number of connections and for example only allow server to use them:

- uC sends `AT+CIPSERVERCONN=1,0`
- uC sends `AT+CIPSERVERCONN=1,1`
- uC sends `AT+CIPSERVERCONN=1,2`

These 3 commands would enable connections `0,1,2` only for server. If ESP got more than 3 connections at a time, they should wait before one of these 3 is available again.

If we then try `AT+CIPSTART=1,...` from uC, we should got an error because connection is reserved for server only! In this case, we can use connections `4,5` for client.

---
This allows us to have better control from uC, specially on devices with small amount of RAM. It also gives is master control from MCU that we control server connections, just like ESP controls them with LwIP stack.

I'm waiting for your response!

**Comment by exeron** [comment]
At least limiting the connections should be done.
Makes no sense using full 5 connections if you don't need them. From a MCU perspective, that implies a waste of resources, more things to deal with.

Currently what ESP in server mode does if all the current connections are in use, and a new one is coming, is just not connectiong. The client will have a timeout or sort of.
What you say about "If ESP got more than 3 connections at a time, they should wait before one of these 3 is available again." is already what the ESP does but using the maximum of allowed connections.

The firmware only have to limit this number to the number defined by the user. It shouldn't be a complex modification. Espressif guys are more than capable of this.

AT+CIPSERVERCONNLIMIT=3 

For example, to limit the number of connections in server mode to 3...

In STA client mode, you can limit the connections just not connecting more than need.
In SoftAP mode, you can limit the connections in AP config.
In STA server mode you cannot limit connections... makes not much sense for me and makes a bunch of troubles.

I'm also waiting for Espressiff response.
