### ISSUE TITLE
wifi设置为ap模式后, 系统重启的接口失效

### ISSUE THREAD

**Issue by hznulilingbo** [espressif/ESP8266_NONOS_SDK#282]
先调wifi_set_opmode_current(SOFTAP_MODE)或者wifi_set_opmode(SOFTAP_MODE), 后调system_restart()无法重启系统.

**Comment by xcguang** [comment]
使用如下命令测试是正常的，你哪个版本？
```
AT+CWMODE_CUR=2
AT+RST
```
或者
```
AT+CWMODE_DEF=2
AT+RST
```
