### ISSUE TITLE
Passive mode in 1Mb device?

### ISSUE THREAD

**Issue by gusmanb** [espressif/ESP8266_NONOS_SDK#295]
I have a 1204Kb module and I would need to use the TCP recceive passive mode. It seems that it was implemented in the SDK 3.0 but the SDK doesn't allows me to compile the at firmware for 1Mb size.

Is there any way to use the passive mode with a 1Mb module?

Thanks,

**Comment by uzi18** [comment]
@gusmanb https://github.com/loboris/ESP8266_AT_LoBo/issues/5

**Comment by gusmanb** [comment]
Thanks a lot!

**Comment by xcguang** [comment]
https://github.com/espressif/ESP8266_NONOS_SDK/tree/master/examples/at_nano
