### ISSUE TITLE
AT+SYSTIMESTAMP? for version 1.7.x

### ISSUE THREAD

**Issue by heinemannj** [espressif/ESP8266_NONOS_SDK#297]
AT firmware 1.7.3 doesn't have a command to return time in epoch seconds. 
AT firmware 2 has AT+SYSTIMESTAMP?.
Please implement this feature into 1.7.x too

**Comment by xcguang** [comment]
Hi,
We have no plan to add any new feature in the ESP8266 NONOS SDK, if possible, please use ESP8266 RTOS AT

**Comment by uzi18** [comment]
Or you can try this one: https://github.com/loboris/ESP8266_AT_LoBo/
