### ISSUE TITLE
mbedTLS into main SDK?

### ISSUE THREAD

**Issue by davydnorris** [espressif/ESP8266_NONOS_SDK#3]
Is the mbedTLS version of the SDK going to be merged into the current SDK? Or has the existing SDK been updated?

**Comment by moosilauke18** [comment]
👍

**Comment by wujiangang** [comment]
@davydnorris @moosilauke18 mbedTLS source code have been pushed in third_party folder, please check.

**Comment by davydnorris** [comment]
awesome work!!
