### ISSUE TITLE
[SDK 3.0.3] csum err with ESP 8285

### ISSUE THREAD

**Issue by ThomArmax** [espressif/ESP8266_NONOS_SDK#309]
Hello,

I try to flash the the new AT firmware 1.7.3 onto my ESP 8285. I have tried different bins, and addresses, but each time I get
```
 ets Jan  8 2013,rst cause:2, boot mode:(3,0)

load 0x40100000, len 816, room 16 
tail 0
chksum 0xef
load 0x00000000, len 0, room 8 
tail 0
chksum 0xef
load 0x00000000, len 0, room 0 
tail 0
chksum 0xef
csum 0xef
csum err
ets_main.c 

```

What is the new flash map to be used for ESP 8285 ?

Thanks

**Comment by xcguang** [comment]
How did you flash it? It seems there is no boot.bin in the flash

**Comment by ThomArmax** [comment]
@xcguang I have flashed

| file | addr |
|-----------------------|-----------|
| boot_v1.7.bin             | 0x00000 |
| user1.2048.new.5.bin | 0x01000 |
|esp_init_data_default_v08.bin | 0x1fc000|
|blank.bin | 0xfe000 |
| blank.bni | 0x1fe000 |

**Comment by kriegste** [comment]
Which flash mode did you use (qio, dout, and so on)? On several modules I only was able to use "dout".

**Comment by ThomArmax** [comment]
@kriegste I have no choice, since it's ESP 8285
- SPI SPEED : 40MHz
- SPI MODE (can't change) DOUT
- FLASH SIZE (can't change) 8Mbit
- DoNotChgBin checked

**Comment by ThomArmax** [comment]
@xcguang @kriegste Do you have any idea ? Thanks :)

**Comment by kriegste** [comment]
Check your flash map. If you really have 8Mbit (= 1MB) of flash, there is no address 0x1fc000 or 0x1fe000.
Also, you need the firmware with "1024" in the name.
