### ISSUE TITLE
incorrect declaration of ets_delay_us

### ISSUE THREAD

**Issue by rojer** [espressif/ESP8266_NONOS_SDK#31]
`ets_delay_us` is declared in [osapi.h](https://github.com/espressif/ESP8266_NONOS_SDK/blob/89ba08ee24c9638dc59d61cfd2ef2819f511bfb9/include/osapi.h#L33) as follows:
```
void ets_delay_us(uint16_t us);
```
in fact, its implementation operates on 32-bit argument, not 16-bit. it should be `uint32_t`.

**Comment by wujiangang** [comment]
Thanks, @rojer update in commit 4671b17c
