### ISSUE TITLE
there's no fn to disable hardware interrupts once you start them

### ISSUE THREAD

**Issue by sneakyimp** [espressif/ESP8266_NONOS_SDK#318]
I refer to the [hw_timer](https://github.com/espressif/ESP8266_NONOS_SDK/blob/master/driver_lib/driver/hw_timer.c) functions which are documented in [section 3.2 of this document](https://www.espressif.com/sites/default/files/documentation/2c-esp8266_non_os_sdk_api_reference_en.pdf). You can easily create a timer fn with this code:
```
#include "hw_timer.h";

// interrupt handler fn
ICACHE_RAW_ATTR void my_callback(void) {
  // this function will never stop running once you start the hw interrupt
}

void setup() {
  hw_timer_init(NMI_SOURCE,1);
  hw_timer_set_func(my_callback);
  hw_timer_arm(100); 
}
```
But **there is no way to remove the hardware interrupt** once you've established it. There is no disarm function. Should you call hw_timer_set_fund(NULL) ?

Also, there is no documentation at all abou twhat the second param of hw_timer_init does. And these functions become VERY UNSTABLE if you aren't doing anything in the interrupt handler callback.

**Comment by flameboss** [comment]
Call hw_timer_init with second argument = 0; then in your ISR call hw_timer_arm() if you want to keep it going and do not call it if you want to "disarm."

**Comment by someburner** [comment]
Here's how I do it:

```c
static void ICACHE_RAM_ATTR hw_timer_disarm_internal()
{
    /* Set no reload mode */
    RTC_REG_WRITE(FRC1_CTRL_ADDRESS, DIVIDED_BY_16 | TM_EDGE_INT);

    TM1_EDGE_INT_DISABLE();
    ETS_FRC1_INTR_DISABLE();
}
```
