### ISSUE TITLE
library for SNTP header files.

### ISSUE THREAD

**Issue by ameerhazo** [espressif/ESP8266_NONOS_SDK#337]
Hello everyone, I'm doing a project where I need a timestamp for my payload that I'm sending and for that I thought the SNTP API could help me with this. Unfortunately when building my code, I'm getting the "section `.text' will not fit in region `iram1_0_seg'" error. Is this error even related to me using SNTP in my code?

What library should I include for my Makefile in order for SNTP to be compiled?

**Comment by noizu** [comment]
its a code size issue, try a difererent rom layout. like 1mb + 1mb.

*   Keith Brings *
   President, Noizu Labs, Inc.

*    Email: *
    keith.brings@noizu.com

*    Skype: *
    keith.brings
    (718) 618-4265

**Comment by ameerhazo** [comment]
@noizu Thanks for the tip :D Got my code to work with your help.
