### ISSUE TITLE
nonos在使用ssl时，必须使用sntp吗？

### ISSUE THREAD

**Issue by yujy-xm** [espressif/ESP8266_NONOS_SDK#338]
您好：
在每次ssl连接时，先使用sntp会时启动时间增加，我们通过增加时钟模块记录时间，但如何把时间写入systime呢？

**Comment by yujy-xm** [comment]
或者，如何关闭证书时间检查？

**Comment by davydnorris** [comment]
if you start the sntp service before ssl connect it will just work.

Connect to Wifi, start sntp, wait till sntp is connected (check the time until it is not 0), then connect to ssl
