### ISSUE TITLE
Please compile all libs with -DUSE_OPTIMIZE_PRINTF

### ISSUE THREAD

**Issue by kriegste** [espressif/ESP8266_NONOS_SDK#55]
At least libmbedtls.a and liblwip.a are not compiled with -DUSE_OPTIMIZE_PRINTF in the compiler flags. To save precious RAM, they should be.

Edit: Compiling both libs by myself gives me almost 1k more free heap for my project. I wonder how much more could be gained with the closed source libs?

**Comment by wujiangang** [comment]
@kriegste I have recompile libmbedtls.a & liblwip.a with -DUSE_OPTIMIZE_PRINTF, for other libs, they are all compiled with this define. Thank you for your reminding.
