### ISSUE TITLE
AT feature request: Set number of connections

### ISSUE THREAD

**Issue by MaJerle** [espressif/ESP8266_NONOS_SDK#61]
Feature request for AT. We all know that number of connections is only limited to RAM usage. It would be good if we have AT command to set maximal number of connections such as `AT+SETCONNNUM=x` where x means maximal number of connections.

And then `AT+CIPCLOSE=x` would close all the connections, with the same behavior as it works now.

**Comment by FayeY** [comment]
Hi, sorry that I'm a little confused, is this a duplicate issue with #62 ? Or they are two different requests?

**Comment by MaJerle** [comment]
Hello, as it is stated in description, this are 2 different proposals. One is setting maximal connections using AT command (max connections all together) while another one is setting max number of connections for server.

**Comment by FayeY** [comment]
Hi, the max connections allowed can be set by adding a "at_customLinkMax=n" in user_init() before calling at_init().

**Comment by MaJerle** [comment]
I know but it is not via official AT.

**Comment by FayeY** [comment]
Hi, it is a feature in the official AT, you can add "at_customLinkMax=n" in the official AT. Default is 5.
It is not a command, because that the memory those links will take are pre-set in the source code, then be compiled.

**Comment by MaJerle** [comment]
Cant we change this to dynamic memory usage?

**Comment by FayeY** [comment]
Hi, sorry that it is not dynamic. To be dynamic, it needs a big change in our internal framework, but since the ESP8266 AT is a stable product, and many customers are using it. We prefer not to change it a lot. Thanks.

**Comment by MaJerle** [comment]
Thanks. There is a catch. It is not very stable, I will post another AT feature request  with detailed explanation what happens.
