### ISSUE TITLE
AT+CIPSERVERMAXCONN like in esp32-at

### ISSUE THREAD

**Issue by MaJerle** [espressif/ESP8266_NONOS_SDK#62]
Hello team,

In ESP32-AT there is a command `AT+CIPSERVERMAXCONN`. Is there a plan to integrate the same command here? It would be very useful to limit resources for SERVER only.

What about this implementation here? 
https://github.com/espressif/esp32-at/issues/28

@FayeY can you please comment?

**Comment by FayeY** [comment]
Hi, we will add it in the next release. Thanks for all your valuable advices! :)

**Comment by MaJerle** [comment]
If I have 5 connections all together and 5 connections are assigned to server. Is there a way to tell ESP to not allow client mode, so if I do `AT+CIPSTART=4,...` it returns error?

**Comment by MaJerle** [comment]
Even if I have set MAXCONN to 10, server will still populate only up to 5 connections (0-4), even if I have 20 connections possible in ESP (compiled with my own settings). Something is hardcoded to 5 for some reason.

**Comment by FayeY** [comment]
Hi

> server will still populate only up to 5 connections (0-4), even if I have 20 connections possible in ESP (compiled with my own settings). 

Have you tested it? This should not happen. If you add at_customerLinkMax=9; before at_init, then the ESP server can accept 9 links at most. 
Thanks.

**Comment by MaJerle** [comment]
I tested it. If I open 7 connections to esp acting as server, only 0-4 are open, and I have fo close one to allow next connection ti be processed.

**Comment by FayeY** [comment]
Hi, sorry that we cannot reproduce your problem.. Could you have a try with the user.bin I provided in [issue 77](https://github.com/espressif/ESP8266_NONOS_SDK/issues/77#issuecomment-353017624)

**Comment by FayeY** [comment]
The test project we used is as the attachment, please try to compile and test it. If your problem is still unsolved, please provide your test project, we will have a try with it. Thanks.
[ESP8266_NONOS_SDK-master.zip](https://github.com/espressif/ESP8266_NONOS_SDK/files/1581531/ESP8266_NONOS_SDK-master.zip)

**Comment by MaJerle** [comment]
On the image below you can see how I opened 6 sockets from PC but only 5 of them were successful.

![image](https://user-images.githubusercontent.com/405717/34287609-92392218-e6e8-11e7-8249-4e64a024e74b.png)

Project I used is also here (FLASH conf 2 (512+512)):
[user1.1024.new.2.zip](https://github.com/espressif/ESP8266_NONOS_SDK/files/1581600/user1.1024.new.2.zip)

**Comment by FayeY** [comment]
Have you set at_customerLinkMax=9; before at_init and then re-compile it? 
We have provided our test project in the comment above, you can compile it and have a try.
Thanks.

**Comment by MaJerle** [comment]
When I try compile your example it compiles infinite time saying "user_main.d" is compiled with time in future. If I delete output files and start over, still a problem.

**Comment by FayeY** [comment]
Hi, 
Sorry for the inconvenience.
After checking it with our engineer, it is a limitation in the LWIP [#define linkMax 15](https://github.com/espressif/ESP8266_NONOS_SDK/blob/master/third_party/include/lwip/app/espconn.h#L208).
You can:
1. change the `#define linkMax 15`  
2. then run `./make_lib.sh lwip` in the "ESP8266_NONOS_SDK/third_party" to re-build the LWIP  
3. then re-build the AT bin.  
Please note that too many connections may cause an issue of "out of memory". You can check the memory by command AT+SYSRAM?
Thanks.
