### ISSUE TITLE
Please clarify the difference between system_get_vdd33() and readvdd33()

### ISSUE THREAD

**Issue by kriegste** [espressif/ESP8266_NONOS_SDK#68]
We all know that system_get_vdd33() can only be used under certain circumstances and will return 65535 otherwise. It is all described in the SDK manual.

Now, I have seen multiple projects that use the (undocumented) readvdd33() function instead. They add the declaration

uint32_t readvdd33(void);

and then use it. I have tried that, too. And it gives me a slightly lower value than system_get_vdd33(). But what is it?

**Comment by FayeY** [comment]
Hi, sorry that readvdd33 should not be used, it is not a released API. 
system_get_vdd33 is the official released API for getting vdd33, it is a reliable API after full testing. 
Please use the system_get_vdd33 if you need to get the value of VDD33.
Thanks.
