### ISSUE TITLE
AT Custom cmd size

### ISSUE THREAD

**Issue by sebest06** [espressif/ESP8266_NONOS_SDK#7]
Hi, i am try to send a custom at cmd with a param size equal 200, and when i send the cmd the esp return ERROR. How can i increse a size of the RX buffer for the at custom cmd?
Thanks

**Comment by FayeY** [comment]
Hi, sorry that it is limited to 128 bytes, cannot be increased to 200 bytes.

**Comment by sebest06** [comment]
Thank, ok, but this limitation is a hardware limitation? Anyway i solved my problem, i send the information splited.

Thank you!
