### ISSUE TITLE
A little Issues 。。。

### ISSUE THREAD

**Issue by xuhongv** [espressif/ESP8266_NONOS_SDK#95]
- 请问使用smartConfig配网成功后，8266可以回调自定义数据返回给App么？

    - 我发现现在APP只能获取到8266的mac地址和IP地址...

**Comment by FayeY** [comment]
你好，配网成功后，ESP8266 可以直接发 UDP 或者 TCP 包给 APP，但是这部分在当前的示例里没有实现，需要你根据实际应用自行实现。
请知悉。谢谢！

**Comment by xuhongv** [comment]
请问你们这个发送mac地址到app的代码可以改么？我想不走tcp或udp，只想直接在你们代码上改..
