### ISSUE TITLE
Nonsense code in mdns_set_hostname in mdns.c (third_party/lwip/core)

### ISSUE THREAD

**Issue by kriegste** [espressif/ESP8266_NONOS_SDK#97]
I am referring to the code starting here
https://github.com/espressif/ESP8266_NONOS_SDK/blob/master/third_party/lwip/core/mdns.c#L964

If I set the hostname to e.g. "testing" and later change it to "esp", it becomes "espting" and not "esp".
That it because os_strncpy is called with the length of the new string omitting the \0 character at the end.
Also, where does the magic number 3 come from?

If I change the code to this:

```
void ICACHE_FLASH_ATTR mdns_set_hostname(char *name) {
        if (name == NULL) {
                os_strncpy(host_name, "Espressif", MDNS_NAME_LENGTH);
                return;
        }
        os_strncpy(host_name, name, MDNS_NAME_LENGTH);
}
```

it works great.
There is no need to call os_strlen.
Although called with the full length of MDNS_NAME_LENGTH, os_strncpy will only copy as many characters as there are in "name" (up to \0 to be precise) and pad all the rest of "host_name" with \0. This is exactly the behavior we desire here.

**Comment by xcguang** [comment]
Have fixed it, please try it again, I will close this issue, if the problem persists, please reopen it again.
